-- 020: 网盘账号管理与链接转存 (PostgreSQL) — feature 047

CREATE TABLE IF NOT EXISTS pan_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform TEXT NOT NULL,
    display_name TEXT NOT NULL,
    credential_cipher TEXT NOT NULL,
    credential_nonce TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    target_dir TEXT NOT NULL,
    capacity_bytes BIGINT,
    last_checked_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_pan_accounts_platform ON pan_accounts(platform);

CREATE TABLE IF NOT EXISTS share_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES pan_accounts(id) ON DELETE CASCADE,
    file_name TEXT NOT NULL,
    share_url TEXT NOT NULL,
    extract_code TEXT,
    remote_file_id TEXT,
    expires_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_share_records_account ON share_records(account_id);

CREATE TABLE IF NOT EXISTS transfer_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_url TEXT NOT NULL,
    source_type TEXT NOT NULL,
    source_platform TEXT,
    extract_code TEXT,
    target_account_id BIGINT NOT NULL REFERENCES pan_accounts(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'pending',
    failure_reason TEXT,
    share_id BIGINT REFERENCES share_records(id),
    source_origin TEXT NOT NULL DEFAULT 'manual',
    idempotency_key TEXT NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    started_at TIMESTAMP,
    completed_at TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_transfer_tasks_idem ON transfer_tasks(idempotency_key);
CREATE INDEX IF NOT EXISTS idx_transfer_tasks_status ON transfer_tasks(status);
CREATE INDEX IF NOT EXISTS idx_transfer_tasks_account ON transfer_tasks(target_account_id);

CREATE TABLE IF NOT EXISTS api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_name TEXT NOT NULL,
    key_hash TEXT NOT NULL UNIQUE,
    key_prefix TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'enabled',
    quota_limit INTEGER NOT NULL DEFAULT 0,
    quota_used INTEGER NOT NULL DEFAULT 0,
    quota_reset_at TIMESTAMP,
    rate_limit_qps INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    revoked_at TIMESTAMP,
    rotated_at TIMESTAMP
);
