use base64::Engine;
use clap::Parser;
use std::path::{Path, PathBuf};

/// Telegram 消息转发工具
#[derive(Parser, Debug, Clone)]
#[command(name = "tgTool", about = "Telegram 消息转发工具", version)]
pub struct Config {
    /// 服务端口
    #[arg(long, default_value = "3000", env = "PORT")]
    pub port: u16,

    /// 日志目录
    #[arg(long, env = "LOG_DIR")]
    pub log_dir: Option<PathBuf>,

    /// 日志级别
    #[arg(long, default_value = "info", env = "RUST_LOG")]
    pub rust_log: String,

    /// Telegram 客户端存储路径
    #[arg(long, default_value = "./tg_store", env = "TG_STORE")]
    pub tg_store: PathBuf,

    /// Telegram APP ID
    #[arg(long, default_value = "0", env = "TG_APP_ID")]
    pub tg_app_id: i32,

    /// Telegram APP Hash
    #[arg(long, default_value = "", env = "TG_APP_HASH")]
    pub tg_app_hash: String,

    /// 数据库连接串（留空使用 SQLite）
    #[arg(long, default_value = "", env = "SQL_DSN")]
    pub sql_dsn: String,

    /// Redis 连接串（留空使用内存存储）
    #[arg(long, default_value = "", env = "REDIS_CONN_STRING")]
    pub redis_conn_string: String,

    /// Session 密钥（启动期强制校验：非空 / 非默认值 / ≥32 字符；feature 027 SEC-001）
    #[arg(long, default_value = "", env = "SESSION_SECRET")]
    pub session_secret: String,

    /// 单 IP 速率限制（请求数/窗口期）
    #[arg(long, default_value = "100", env = "RATE_LIMIT_MAX")]
    pub rate_limit_max: usize,

    /// 速率限制窗口（秒）
    #[arg(long, default_value = "60", env = "RATE_LIMIT_WINDOW")]
    pub rate_limit_window_secs: u64,

    /// 网盘凭据加密主密钥（base64 编码的 32 字节随机；AES-256-GCM 加解密网盘 Cookie/Token，feature 047）
    #[arg(long, default_value = "", env = "PAN_CRED_KEY")]
    pub pan_cred_key: String,

    /// 直链上传本地中转目录（feature 047）
    #[arg(long, default_value = "./.tmp/pan-staging", env = "PAN_STAGING_DIR")]
    pub pan_staging_dir: PathBuf,
}

impl Config {
    pub fn load() -> Self {
        // Load .env file (ignore error if not found)，保留路径供后续持久化使用
        let env_path = dotenvy::dotenv().ok();

        let mut config = Config::parse();

        // feature 027 SEC-001：启动期强制校验 SESSION_SECRET（拒绝空 / 默认值 / 过短）
        // 生产环境 fail-fast；测试环境仅提示（测试不模拟生产 secret，
        // 校验逻辑由 validate_session_secret 单测覆盖，见 SC-001）
        if let Err(msg) = crate::services::crypto::validate_session_secret(&config.session_secret) {
            if cfg!(not(test)) {
                panic!("启动失败 — {msg}");
            } else {
                eprintln!("[test] SESSION_SECRET 校验跳过: {msg}");
            }
        }

        // feature 047：PAN_CRED_KEY 缺失时自动生成 32 字节随机（base64）并追加到 .env，
        // 保证后续重启复用同一密钥（避免已加密凭据无法解密）。测试环境跳过。
        if config.pan_cred_key.trim().is_empty() && !cfg!(test) {
            match ensure_pan_cred_key(env_path.as_deref()) {
                Ok(Some(key)) => {
                    config.pan_cred_key = key;
                }
                Ok(None) => {
                    eprintln!(
                        "[warn] PAN_CRED_KEY 未配置且无 .env 可写入；网盘账号功能不可用（请手动设置）"
                    );
                }
                Err(e) => {
                    eprintln!(
                        "[warn] PAN_CRED_KEY 自动生成/持久化失败: {e}；网盘账号功能不可用（请手动设置）"
                    );
                }
            }
        }

        // Ensure tg_store directory exists
        if !config.tg_store.exists() {
            std::fs::create_dir_all(&config.tg_store).expect("Failed to create tg_store directory");
        }

        config
    }

    /// Get the database URL. Falls back to SQLite if SQL_DSN is empty.
    pub fn database_url(&self) -> String {
        if self.sql_dsn.is_empty() {
            "sqlite:./data.db?mode=rwc".to_string()
        } else {
            self.sql_dsn.clone()
        }
    }

    /// Check if using PostgreSQL
    pub fn is_postgres(&self) -> bool {
        self.sql_dsn.starts_with("postgres")
    }
}

/// 若 PAN_CRED_KEY 缺失：生成 32 字节 CSPRNG 随机 → base64 编码 → 追加写入 .env。
///
/// 返回值：
/// - `Ok(Some(key))` — 已生成并写入 .env，调用方应将其赋给 `config.pan_cred_key`
/// - `Ok(None)` — 无 .env 路径可用（用户用环境变量部署），跳过；调用方应告警
/// - `Err(msg)` — IO 失败；调用方应告警且不修改 config（保持空，网盘功能禁用）
///
/// 注意：写入失败时 **不** 让进程 panic —— 重启时仍可重新生成（此时还没有任何加密数据，
/// 不会造成解密失败）；一旦生成成功并已有账号凭据，后续就绝不能换密钥。
fn ensure_pan_cred_key(env_path: Option<&Path>) -> Result<Option<String>, String> {
    use std::io::Write;

    let path = match env_path {
        Some(p) => p,
        None => return Ok(None),
    };

    let bytes = generate_random_32();
    let key = base64::engine::general_purpose::STANDARD.encode(bytes);

    let mut f = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(path)
        .map_err(|e| format!("打开 .env 失败 ({}): {e}", path.display()))?;

    let line = format!(
        "\n# auto-generated by tgTool (feature 047 PAN_CRED_KEY) — 切勿提交到 git\nPAN_CRED_KEY={key}\n"
    );
    f.write_all(line.as_bytes())
        .map_err(|e| format!("写入 .env 失败 ({}): {e}", path.display()))?;

    tracing::info!("PAN_CRED_KEY 已自动生成并持久化到 {}", path.display());
    Ok(Some(key))
}

/// 生成 32 字节密码学安全随机数。复用 uuid v4（CSPRNG）避免引入额外 rand 依赖。
fn generate_random_32() -> [u8; 32] {
    let mut bytes = [0u8; 32];
    let u1 = uuid::Uuid::new_v4();
    let u2 = uuid::Uuid::new_v4();
    bytes[..16].copy_from_slice(u1.as_bytes());
    bytes[16..].copy_from_slice(u2.as_bytes());
    bytes
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_config(sql_dsn: &str) -> Config {
        Config {
            port: 3000,
            log_dir: None,
            rust_log: "info".to_string(),
            tg_store: PathBuf::from("./tg_store"),
            tg_app_id: 12345,
            tg_app_hash: "testhash".to_string(),
            sql_dsn: sql_dsn.to_string(),
            redis_conn_string: String::new(),
            session_secret: "test-secret-0123456789abcdef0123456789".to_string(),
            rate_limit_max: 100,
            rate_limit_window_secs: 60,
            pan_cred_key: String::new(),
            pan_staging_dir: PathBuf::from("./.tmp/pan-staging"),
        }
    }

    #[test]
    fn test_database_url_default_sqlite() {
        let config = make_config("");
        let url = config.database_url();
        assert_eq!(url, "sqlite:./data.db?mode=rwc");
    }

    #[test]
    fn test_database_url_postgres_dsn() {
        let config = make_config("postgres://user:pass@localhost/db");
        let url = config.database_url();
        assert_eq!(url, "postgres://user:pass@localhost/db");
    }

    #[test]
    fn test_database_url_sqlite_dsn() {
        let config = make_config("sqlite:./custom.db?mode=rwc");
        let url = config.database_url();
        assert_eq!(url, "sqlite:./custom.db?mode=rwc");
    }

    #[test]
    fn test_is_postgres_true() {
        let config = make_config("postgres://user:pass@host/db");
        assert!(config.is_postgres());
    }

    #[test]
    fn test_is_postgres_false_empty() {
        let config = make_config("");
        assert!(!config.is_postgres());
    }

    #[test]
    fn test_is_postgres_false_sqlite() {
        let config = make_config("sqlite:./test.db");
        assert!(!config.is_postgres());
    }

    #[test]
    fn test_is_postgres_postgresql_prefix() {
        let config = make_config("postgresql://host/db");
        assert!(config.is_postgres()); // "postgresql" starts with "postgres"
    }

    #[test]
    fn test_rate_limit_defaults() {
        let config = make_config("");
        assert_eq!(config.rate_limit_max, 100);
        assert_eq!(config.rate_limit_window_secs, 60);
    }

    /// 唯一文件名，避免并发测试互相覆盖
    fn tmp_env_path(tag: &str) -> PathBuf {
        let mut p = std::env::temp_dir();
        p.push(format!(
            "tgTool-test-env-{}-{}-{}.env",
            tag,
            std::process::id(),
            uuid::Uuid::new_v4()
        ));
        p
    }

    #[test]
    fn test_ensure_pan_cred_key_generates_and_persists() {
        let path = tmp_env_path("gen");
        std::fs::write(&path, "PORT=3000\nSESSION_SECRET=x\n").unwrap();

        let result = ensure_pan_cred_key(Some(&path)).expect("应成功");
        let key = result.expect("应返回 Some");

        // 1. 返回的 key 是合法 base64，解码后 32 字节
        let raw = base64::engine::general_purpose::STANDARD
            .decode(&key)
            .expect("合法 base64");
        assert_eq!(raw.len(), 32, "PAN_CRED_KEY 必须是 32 字节");

        // 2. .env 中已追加该行
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(
            content.contains(&format!("PAN_CRED_KEY={key}")),
            ".env 应包含 PAN_CRED_KEY 行"
        );

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_ensure_pan_cred_key_skips_when_no_env_path() {
        // 用户用环境变量部署（无 .env 文件），不应误创建文件
        let result = ensure_pan_cred_key(None).expect("None 路径不应报错");
        assert!(result.is_none(), "无 env_path 应返回 Ok(None)");
    }

    #[test]
    fn test_ensure_pan_cred_key_creates_env_if_missing() {
        // .env 不存在但路径已知（首次部署）→ 应自动创建文件
        let path = tmp_env_path("create");
        assert!(!path.exists(), "前置：文件不存在");

        let result = ensure_pan_cred_key(Some(&path)).expect("应成功");
        assert!(result.is_some(), "应返回 Some");
        assert!(path.exists(), ".env 文件应被创建");

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_generate_random_32_is_unique_and_correct_length() {
        // 连续两次不应相同（CSPRNG）
        let a = generate_random_32();
        let b = generate_random_32();
        assert_eq!(a.len(), 32);
        assert_eq!(b.len(), 32);
        assert_ne!(a, b, "两次生成应不同");
    }
}
